// Glue code to call into WASM functions generated by Emscripten
// Assumes Module is defined in ui_demo.js (generated by emcc)

function ready() {
  const screens = {
    boot: Module.cwrap('ui_show_boot', null, []),
    home: Module.cwrap('ui_show_home', null, []),
    music: Module.cwrap('ui_show_music', null, []),
    settings: Module.cwrap('ui_show_settings', null, []),
  };

  document.querySelectorAll('#controls button').forEach((btn) => {
    btn.addEventListener('click', () => {
      const scr = btn.dataset.screen;
      if (screens[scr]) {
        screens[scr]();
      }
    });
  });

  // Default to boot screen once runtime is ready
  screens.boot();
}

// Emscripten runtime calls Module.onRuntimeInitialized when WASM ready
typeof Module !== 'undefined'
  ? (Module.onRuntimeInitialized = ready)
  : console.error('Module is not defined');
